version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: cleanit-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleanit

    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./backend/sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cleanit"]
      interval: 3s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cleanit-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cleanit
      PORT: 8080

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cleanit-frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "80:80"
    environment:
      NODE_ENV: production

volumes:
  dbdata:
